"""Initial migration

Revision ID: 32d8b53de4e8
Revises: 43b4f0d09754
Create Date: 2026-05-07 20:59:44.907019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32d8b53de4e8'
down_revision = '43b4f0d09754'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
