"""Initial migration

Revision ID: 0c82c59378d3
Revises: 32d8b53de4e8
Create Date: 2026-05-07 21:03:28.016319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c82c59378d3'
down_revision = '32d8b53de4e8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
